import {
  User,
  Task,
  DashboardStats,
  AgentStats,
  WeeklyTrend,
  ActivityItem,
  GeoPoint,
  Region,
  Notification,
  TaskStatsByExploitation,
  TaskStatsByZone,
  TaskStatsByCity,
  TaskStatsByRegion,
  ElectricRegion,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@minee.cm",
    firstName: "Jean-Pierre",
    lastName: "Nguema",
    role: "admin",
    department: "Direction Générale",
    phone: "+237 6 99 00 00 01",
    isActive: true,
    createdAt: "2024-01-15T08:00:00Z",
    lastLogin: "2024-03-20T14:30:00Z",
    tasksAssigned: 0,
    tasksCompleted: 0,
    occupancyRate: 0,
  },
  {
    id: "2",
    email: "marie.ekotto@minee.cm",
    firstName: "Marie",
    lastName: "Ekotto",
    role: "team_lead",
    department: "Unité SIG",
    phone: "+237 6 99 00 00 02",
    isActive: true,
    createdAt: "2024-01-20T09:00:00Z",
    lastLogin: "2024-03-20T16:45:00Z",
    tasksAssigned: 45,
    tasksCompleted: 42,
    occupancyRate: 85,
  },
  {
    id: "3",
    email: "paul.mvondo@minee.cm",
    firstName: "Paul",
    lastName: "Mvondo",
    role: "validation_agent",
    department: "Contrôle Qualité",
    phone: "+237 6 99 00 00 03",
    isActive: true,
    createdAt: "2024-02-01T10:00:00Z",
    lastLogin: "2024-03-20T15:20:00Z",
    tasksAssigned: 120,
    tasksCompleted: 108,
    occupancyRate: 72,
  },
  {
    id: "4",
    email: "agnes.fotso@minee.cm",
    firstName: "Agnès",
    lastName: "Fotso",
    role: "processing_agent",
    department: "Traitement des Données",
    phone: "+237 6 99 00 00 04",
    isActive: true,
    createdAt: "2024-02-10T11:00:00Z",
    lastLogin: "2024-03-20T17:00:00Z",
    tasksAssigned: 85,
    tasksCompleted: 78,
    occupancyRate: 91,
  },
  {
    id: "5",
    email: "olivier.nkono@minee.cm",
    firstName: "Olivier",
    lastName: "Nkono",
    role: "processing_agent",
    department: "Traitement des Données",
    phone: "+237 6 99 00 00 05",
    isActive: true,
    createdAt: "2024-02-15T08:30:00Z",
    lastLogin: "2024-03-20T14:00:00Z",
    tasksAssigned: 92,
    tasksCompleted: 65,
    occupancyRate: 68,
  },
  {
    id: "6",
    email: "sylvie.ateba@minee.cm",
    firstName: "Sylvie",
    lastName: "Ateba",
    role: "validation_agent",
    department: "Contrôle Qualité",
    phone: "+237 6 99 00 00 06",
    isActive: false,
    createdAt: "2024-02-20T09:00:00Z",
    lastLogin: "2024-03-15T12:00:00Z",
    tasksAssigned: 50,
    tasksCompleted: 50,
    occupancyRate: 0,
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "task-001",
    type: "duplicate",
    status: "pending",
    priority: "high",
    title: "Doublon détecté - Compteur #A2345",
    description: "Deux entrées similaires trouvées pour le même emplacement",
    assignedTo: "4",
    createdAt: "2024-03-20T08:00:00Z",
    updatedAt: "2024-03-20T08:00:00Z",
    data: {
      koboId: "KBO-2345",
      eneoId: "ENEO-2345",
      location: "Yaoundé, Bastos",
    },
    sourceData: {
      id: "KBO-2345",
      name: "Compteur Résidentiel",
      address: "123 Rue Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    targetData: {
      id: "KBO-2346",
      name: "Compteur Résidentiel",
      address: "123 Rue de Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    similarity: 94,
    confidence: 87,
  },
  {
    id: "task-002",
    type: "difference",
    status: "in_progress",
    priority: "medium",
    title: "Différence Kobo/Eneo - Zone Bonanjo",
    description: "Données de puissance différentes entre les sources",
    assignedTo: "5",
    createdAt: "2024-03-19T14:30:00Z",
    updatedAt: "2024-03-20T10:15:00Z",
    data: {
      koboId: "KBO-5678",
      eneoId: "ENEO-5678",
      location: "Douala, Bonanjo",
      field: "power",
    },
    sourceData: {
      id: "KBO-5678",
      power: "10kVA",
      lastReading: "2024-03-15",
    },
    targetData: {
      id: "ENEO-5678",
      power: "15kVA",
      lastReading: "2024-03-10",
    },
  },
  {
    id: "task-003",
    type: "new_kobo",
    status: "completed",
    priority: "low",
    title: "Nouvelle entrée Kobo - Secteur 7",
    description: "Nouveau compteur enregistré via Kobo sans correspondance Eneo",
    assignedTo: "4",
    createdAt: "2024-03-18T09:00:00Z",
    updatedAt: "2024-03-19T16:00:00Z",
    completedAt: "2024-03-19T16:00:00Z",
    data: {
      koboId: "KBO-9012",
      location: "Yaoundé, Mvan",
    },
    sourceData: {
      id: "KBO-9012",
      name: "Nouveau Point de Livraison",
      address: "45 Avenue Mvan",
      type: "Triphasé",
      power: "20kVA",
      coordinates: { lat: 3.8480, lng: 11.5021 },
    },
  },
  {
    id: "task-004",
    type: "missing_eneo",
    status: "validated",
    priority: "high",
    title: "Données Eneo manquantes - Quartier Akwa",
    description: "Point référencé dans Eneo absent de Kobo",
    assignedTo: "5",
    createdAt: "2024-03-17T11:00:00Z",
    updatedAt: "2024-03-20T09:00:00Z",
    completedAt: "2024-03-19T14:00:00Z",
    validatedAt: "2024-03-20T09:00:00Z",
    validatedBy: "3",
    validationComment: "Données vérifiées sur le terrain",
    data: {
      eneoId: "ENEO-3456",
      location: "Douala, Akwa",
    },
    targetData: {
      id: "ENEO-3456",
      name: "Point Commercial",
      address: "78 Boulevard Akwa",
      type: "Triphasé",
      power: "50kVA",
    },
  },
  {
    id: "task-005",
    type: "duplicate",
    status: "rejected",
    priority: "medium",
    title: "Doublon suspect - Zone Industrielle",
    description: "Vérification requise pour doublon potentiel",
    assignedTo: "4",
    createdAt: "2024-03-16T15:00:00Z",
    updatedAt: "2024-03-18T10:00:00Z",
    completedAt: "2024-03-17T17:00:00Z",
    validatedAt: "2024-03-18T10:00:00Z",
    validatedBy: "3",
    validationComment: "Ce ne sont pas des doublons, installations différentes",
    data: {
      koboId: "KBO-7890",
      location: "Douala, Bonabéri",
    },
    similarity: 72,
    confidence: 45,
  },
  {
    id: "task-006",
    type: "difference",
    status: "pending",
    priority: "high",
    title: "Écart de coordonnées GPS",
    description: "Position GPS différente de plus de 100m",
    createdAt: "2024-03-20T07:00:00Z",
    updatedAt: "2024-03-20T07:00:00Z",
    data: {
      koboId: "KBO-1122",
      eneoId: "ENEO-1122",
      location: "Garoua, Centre",
      distanceMeters: 156,
    },
  },
  {
    id: "task-007",
    type: "new_kobo",
    status: "in_progress",
    priority: "medium",
    title: "Lot de 15 nouveaux compteurs",
    description: "Import massif de données terrain",
    assignedTo: "5",
    createdAt: "2024-03-20T06:00:00Z",
    updatedAt: "2024-03-20T11:00:00Z",
    data: {
      batchId: "BATCH-2024-03-20",
      count: 15,
      region: "Nord",
    },
  },
];

// Dashboard Statistics
export const mockDashboardStats: DashboardStats = {
  totalTasks: 1247,
  pending: 234,
  inProgress: 156,
  completed: 687,
  validated: 612,
  rejected: 45,
  processingRate: 78.5,
  validationRate: 93.2,
  avgProcessingTime: 2.4,
};

// Agent Statistics
export const mockAgentStats: AgentStats[] = [
  {
    userId: "4",
    user: mockUsers[3],
    tasksAssigned: 85,
    tasksCompleted: 78,
    tasksValidated: 72,
    tasksRejected: 6,
    occupancyRate: 91,
    avgProcessingTime: 1.8,
    efficiency: 92,
  },
  {
    userId: "5",
    user: mockUsers[4],
    tasksAssigned: 92,
    tasksCompleted: 65,
    tasksValidated: 58,
    tasksRejected: 7,
    occupancyRate: 68,
    avgProcessingTime: 2.9,
    efficiency: 71,
  },
  {
    userId: "3",
    user: mockUsers[2],
    tasksAssigned: 120,
    tasksCompleted: 108,
    tasksValidated: 108,
    tasksRejected: 0,
    occupancyRate: 72,
    avgProcessingTime: 1.2,
    efficiency: 90,
  },
];

// Weekly Trend
export const mockWeeklyTrend: WeeklyTrend[] = [
  { date: "2024-03-14", completed: 45, validated: 42, rejected: 3 },
  { date: "2024-03-15", completed: 52, validated: 48, rejected: 4 },
  { date: "2024-03-16", completed: 38, validated: 35, rejected: 2 },
  { date: "2024-03-17", completed: 28, validated: 26, rejected: 1 },
  { date: "2024-03-18", completed: 61, validated: 58, rejected: 3 },
  { date: "2024-03-19", completed: 55, validated: 52, rejected: 2 },
  { date: "2024-03-20", completed: 42, validated: 38, rejected: 4 },
];

// Recent Activity
export const mockActivity: ActivityItem[] = [
  {
    id: "act-001",
    type: "task_validated",
    description: "Tâche #004 validée",
    timestamp: "2024-03-20T09:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-004",
  },
  {
    id: "act-002",
    type: "task_completed",
    description: "Traitement terminé - Lot 15 compteurs",
    timestamp: "2024-03-20T08:30:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-007",
  },
  {
    id: "act-003",
    type: "task_created",
    description: "Nouveau doublon détecté automatiquement",
    timestamp: "2024-03-20T08:00:00Z",
    taskId: "task-001",
  },
  {
    id: "act-004",
    type: "task_rejected",
    description: "Tâche #005 rejetée après vérification",
    timestamp: "2024-03-18T10:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-005",
  },
  {
    id: "act-005",
    type: "user_created",
    description: "Nouvel agent ajouté au système",
    timestamp: "2024-03-17T14:00:00Z",
    userId: "1",
    user: mockUsers[0],
  },
];

// GeoPoints for Map
export const mockGeoPoints: GeoPoint[] = [
  { id: "geo-001", lat: 3.8480, lng: 11.5021, type: "kobo", status: "completed", data: { name: "Point A" } },
  { id: "geo-002", lat: 3.8550, lng: 11.5150, type: "eneo", status: "validated", data: { name: "Point B" } },
  { id: "geo-003", lat: 3.8600, lng: 11.4900, type: "processed", status: "in_progress", data: { name: "Point C" } },
  { id: "geo-004", lat: 4.0511, lng: 9.7679, type: "kobo", status: "pending", data: { name: "Point D" } },
  { id: "geo-005", lat: 4.0600, lng: 9.7800, type: "eneo", status: "completed", data: { name: "Point E" } },
  { id: "geo-006", lat: 4.0450, lng: 9.7550, type: "kobo", status: "validated", data: { name: "Point F" } },
  { id: "geo-007", lat: 5.9631, lng: 10.1591, type: "processed", status: "completed", data: { name: "Point G" } },
  { id: "geo-008", lat: 9.3265, lng: 13.3972, type: "kobo", status: "pending", data: { name: "Point H" } },
];

// Regions
export const mockRegions: Region[] = [
  { id: "reg-001", name: "Centre", code: "CE", pointsCount: 456, completionRate: 78 },
  { id: "reg-002", name: "Littoral", code: "LT", pointsCount: 523, completionRate: 85 },
  { id: "reg-003", name: "Ouest", code: "OU", pointsCount: 312, completionRate: 62 },
  { id: "reg-004", name: "Nord", code: "NO", pointsCount: 189, completionRate: 45 },
  { id: "reg-005", name: "Sud", code: "SU", pointsCount: 145, completionRate: 71 },
  { id: "reg-006", name: "Est", code: "ES", pointsCount: 98, completionRate: 55 },
  { id: "reg-007", name: "Adamaoua", code: "AD", pointsCount: 87, completionRate: 48 },
  { id: "reg-008", name: "Nord-Ouest", code: "NW", pointsCount: 134, completionRate: 58 },
  { id: "reg-009", name: "Sud-Ouest", code: "SW", pointsCount: 167, completionRate: 67 },
  { id: "reg-010", name: "Extrême-Nord", code: "EN", pointsCount: 136, completionRate: 42 },
];

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "new_task",
    title: "Nouvelle tâche assignée",
    message: "Un nouveau doublon a été détecté et vous a été assigné",
    isRead: false,
    createdAt: "2024-03-20T08:00:00Z",
    linkTo: "/processing/duplicates/task-001",
  },
  {
    id: "notif-002",
    type: "task_validated",
    title: "Tâche validée",
    message: "Votre traitement #004 a été validé par Paul Mvondo",
    isRead: false,
    createdAt: "2024-03-20T09:00:00Z",
    linkTo: "/validation/task-004",
  },
  {
    id: "notif-003",
    type: "task_rejected",
    title: "Tâche rejetée",
    message: "Le traitement #005 a été rejeté. Veuillez vérifier les commentaires.",
    isRead: true,
    createdAt: "2024-03-18T10:00:00Z",
    linkTo: "/validation/task-005",
  },
  {
    id: "notif-004",
    type: "system",
    title: "Maintenance programmée",
    message: "Une maintenance est prévue le 25 mars de 02h à 04h",
    isRead: true,
    createdAt: "2024-03-17T12:00:00Z",
  },
];

// Electric Regions (ENEO Organization)
export const mockElectricRegions: ElectricRegion[] = [
  { id: "er-001", name: "Région Électrique Douala Ouest", code: "RDUO", city: "Douala" },
  { id: "er-002", name: "Région Électrique Douala Est", code: "RDUE", city: "Douala" },
  { id: "er-003", name: "Région Électrique Douala Centre", code: "RDUC", city: "Douala" },
  { id: "er-004", name: "Région Électrique Yaoundé Nord", code: "RYN", city: "Yaoundé" },
  { id: "er-005", name: "Région Électrique Yaoundé Sud", code: "RYS", city: "Yaoundé" },
  { id: "er-006", name: "Région Électrique Yaoundé Centre", code: "RYC", city: "Yaoundé" },
  { id: "er-007", name: "Région Électrique Garoua", code: "RG", city: "Garoua" },
  { id: "er-008", name: "Région Électrique Bamenda", code: "RB", city: "Bamenda" },
  { id: "er-009", name: "Région Électrique Buea", code: "RBU", city: "Buea" },
  { id: "er-010", name: "Région Électrique Bertoua", code: "RBE", city: "Bertoua" },
];

// Task Stats by Region
export const mockTaskStatsByRegion: TaskStatsByRegion[] = [
  {
    region: mockElectricRegions[0],
    totalTasks: 234,
    pending: 45,
    inProgress: 28,
    completed: 145,
    validated: 140,
    rejected: 16,
    completionRate: 62,
  },
  {
    region: mockElectricRegions[1],
    totalTasks: 198,
    pending: 32,
    inProgress: 25,
    completed: 128,
    validated: 122,
    rejected: 13,
    completionRate: 65,
  },
  {
    region: mockElectricRegions[2],
    totalTasks: 167,
    pending: 28,
    inProgress: 18,
    completed: 112,
    validated: 108,
    rejected: 9,
    completionRate: 67,
  },
  {
    region: mockElectricRegions[3],
    totalTasks: 245,
    pending: 52,
    inProgress: 35,
    completed: 148,
    validated: 142,
    rejected: 10,
    completionRate: 60,
  },
  {
    region: mockElectricRegions[4],
    totalTasks: 212,
    pending: 38,
    inProgress: 22,
    completed: 137,
    validated: 132,
    rejected: 15,
    completionRate: 65,
  },
];

// Task Stats by City
export const mockTaskStatsByCity: TaskStatsByCity[] = [
  {
    city: "Douala",
    regions: mockElectricRegions.slice(0, 3),
    totalTasks: 599,
    pending: 105,
    completionRate: 65,
  },
  {
    city: "Yaoundé",
    regions: mockElectricRegions.slice(3, 6),
    totalTasks: 512,
    pending: 92,
    completionRate: 63,
  },
  {
    city: "Garoua",
    regions: [mockElectricRegions[6]],
    totalTasks: 156,
    pending: 28,
    completionRate: 58,
  },
  {
    city: "Bamenda",
    regions: [mockElectricRegions[7]],
    totalTasks: 134,
    pending: 24,
    completionRate: 61,
  },
];

// Task Stats by Zone
export const mockTaskStatsByZone: TaskStatsByZone[] = [
  { zone: "Zone Résidentielle Nord", totalTasks: 234, completed: 145 },
  { zone: "Zone Commerciale", totalTasks: 189, completed: 128 },
  { zone: "Zone Industrielle", totalTasks: 156, completed: 92 },
  { zone: "Zone Administrative", totalTasks: 98, completed: 67 },
  { zone: "Zone Rurale", totalTasks: 145, completed: 78 },
];

// Task Stats by Exploitation
export const mockTaskStatsByExploitation: TaskStatsByExploitation[] = [
  { exploitationId: "exp-001", exploitationName: "Exploitation Douala Centre", totalTasks: 128, completed: 89, avgProcessingTime: 2.1 },
  { exploitationId: "exp-002", exploitationName: "Exploitation Douala Ouest", totalTasks: 112, completed: 78, avgProcessingTime: 1.9 },
  { exploitationId: "exp-003", exploitationName: "Exploitation Yaoundé Nord", totalTasks: 145, completed: 98, avgProcessingTime: 2.3 },
  { exploitationId: "exp-004", exploitationName: "Exploitation Yaoundé Centre", totalTasks: 134, completed: 92, avgProcessingTime: 2.0 },
  { exploitationId: "exp-005", exploitationName: "Exploitation Garoua", totalTasks: 87, completed: 52, avgProcessingTime: 2.8 },
];