// lib/api/mock-data.ts
import {
  User,
  Task,
  DashboardStats,
  AgentStats,
  WeeklyTrend,
  ActivityItem,
  GeoPoint,
  Region,
  Notification,
  TaskStatsByExploitation,
  TaskStatsByZone,
  TaskStatsByCity,
  TaskStatsByRegion,
  ElectricRegion,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@minee.cm",
    firstName: "Jean-Pierre",
    lastName: "Nguema",
    company: "GROUPEMENT",
    role: "admin",
    phone: "+237 6 99 00 00 01",
    isActive: true,
    occupancyRate: 50,
    createdAt: "2026-04-01T08:00:00Z",
    lastLogin: "2026-04-01T09:30:00Z",
    tasksAssigned: 0,
    tasksCompleted: 0,
    status: 'en ligne'
  },
  {
    id: "2",
    email: "marie.ekotto@minee.cm",
    firstName: "Marie",
    lastName: "Ekotto",
    company: "GROUPEMENT",
    role: "team_lead",
    phone: "+237 6 99 00 00 02",
    isActive: true,
    createdAt: "2026-04-01T09:00:00Z",
    lastLogin: "2026-04-01T08:15:00Z",
    tasksAssigned: 48,
    occupancyRate: 90,
    tasksCompleted: 45,
    status: 'en ligne'
  },
  {
    id: "3",
    email: "paul.mvondo@minee.cm",
    firstName: "Paul",
    lastName: "Mvondo",
    company: "GROUPEMENT",
    role: "validation_agent",
    phone: "+237 6 99 00 00 03",
    isActive: true,
    createdAt: "2026-04-01T10:00:00Z",
    lastLogin: "2026-04-01T10:45:00Z",
    tasksAssigned: 125,
    tasksCompleted: 113,
    occupancyRate: 0,
    status: 'en ligne'
  },
  {
    id: "4",
    email: "agnes.fotso@minee.cm",
    firstName: "Agnès",
    lastName: "Fotso",
    company: "ENEO",
    role: "processing_agent",
    phone: "+237 6 99 00 00 04",
    isActive: true,
    createdAt: "2026-04-01T11:00:00Z",
    lastLogin: "2026-04-01T09:00:00Z",
    tasksAssigned: 90,
    tasksCompleted: 82,
    occupancyRate: 0,
    status: 'en ligne'
  },
  {
    id: "5",
    email: "olivier.nkono@minee.cm",
    firstName: "Olivier",
    lastName: "Nkono",
    company: "ENEO",
    role: "processing_agent",
    phone: "+237 6 99 00 00 05",
    isActive: true,
    createdAt: "2026-04-01T08:30:00Z",
    lastLogin: "2026-04-01T08:30:00Z",
    tasksAssigned: 98,
    occupancyRate: 0,
    tasksCompleted: 71,
    status: 'en ligne'
  },
  {
    id: "6",
    email: "sylvie.ateba@minee.cm",
    firstName: "Sylvie",
    lastName: "Ateba",
    company: "ENEO",
    role: "validation_agent",
    occupancyRate: 0,
    phone: "+237 6 99 00 00 06",
    isActive: true,
    createdAt: "2026-04-01T09:00:00Z",
    lastLogin: "2026-04-01T07:45:00Z",
    tasksAssigned: 55,
    tasksCompleted: 53,
    status: 'en ligne'
  },
];

// Mock Tasks - Tâches pour la semaine du 23 au 26 mars
export const mockTasks: Task[] = [
  // Lundi 23
  {
    id: "task-001",
    type: "duplicate",
    status: "completed",
    priority: "high",
    title: "Doublon détecté - Compteur #A2345",
    description: "Deux entrées similaires trouvées pour le même emplacement",
    assignedTo: "4",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T10:30:00Z",
    completedAt: "2026-04-01T10:30:00Z",
    data: {
      koboId: "KBO-2345",
      eneoId: "ENEO-2345",
      location: "Yaoundé, Bastos",
    },
    sourceData: {
      id: "KBO-2345",
      name: "Compteur Résidentiel",
      address: "123 Rue Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    targetData: {
      id: "KBO-2346",
      name: "Compteur Résidentiel",
      address: "123 Rue de Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    similarity: 94,
    confidence: 87,
  },
  {
    id: "task-002",
    type: "difference",
    status: "validated",
    priority: "medium",
    title: "Différence Kobo/Eneo - Zone Bonanjo",
    description: "Données de puissance différentes entre les sources",
    assignedTo: "5",
    createdAt: "2026-04-01T09:30:00Z",
    updatedAt: "2026-04-01T16:15:00Z",
    completedAt: "2026-04-01T14:00:00Z",
    validatedAt: "2026-04-01T16:15:00Z",
    validatedBy: "3",
    validationComment: "Correction effectuée",
    data: {
      koboId: "KBO-5678",
      eneoId: "ENEO-5678",
      location: "Douala, Bonanjo",
      field: "power",
    },
    sourceData: {
      id: "KBO-5678",
      power: "10kVA",
      lastReading: "2026-04-01",
    },
    targetData: {
      id: "ENEO-5678",
      power: "15kVA",
      lastReading: "2026-04-01",
    },
  },
  {
    id: "task-003",
    type: "new_kobo",
    status: "validated",
    priority: "low",
    title: "Nouvelle entrée Kobo - Secteur 7",
    description: "Nouveau compteur enregistré via Kobo sans correspondance Eneo",
    assignedTo: "4",
    createdAt: "2026-04-01T07:00:00Z",
    updatedAt: "2026-04-01T13:30:00Z",
    completedAt: "2026-04-01T11:00:00Z",
    validatedAt: "2026-04-01T13:30:00Z",
    validatedBy: "3",
    data: {
      koboId: "KBO-9012",
      location: "Yaoundé, Mvan",
    },
    sourceData: {
      id: "KBO-9012",
      name: "Nouveau Point de Livraison",
      address: "45 Avenue Mvan",
      type: "Triphasé",
      power: "20kVA",
      coordinates: { lat: 3.8480, lng: 11.5021 },
    },
  },

  
  {
    id: "task-004",
    type: "missing_eneo",
    status: "completed",
    priority: "high",
    title: "Données Eneo manquantes - Quartier Akwa",
    description: "Point référencé dans Eneo absent de Kobo",
    assignedTo: "5",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T17:00:00Z",
    completedAt: "2026-04-01T17:00:00Z",
    data: {
      eneoId: "ENEO-3456",
      location: "Douala, Akwa",
    },
    targetData: {
      id: "ENEO-3456",
      name: "Point Commercial",
      address: "78 Boulevard Akwa",
      type: "Triphasé",
      power: "50kVA",
    },
  },
  {
    id: "task-005",
    type: "duplicate",
    status: "rejected",
    priority: "medium",
    title: "Doublon suspect - Zone Industrielle",
    description: "Vérification requise pour doublon potentiel",
    assignedTo: "4",
    createdAt: "2026-04-01T14:00:00Z",
    updatedAt: "2026-04-01T18:30:00Z",
    completedAt: "2026-04-01T17:30:00Z",
    validatedAt: "2026-04-01T18:30:00Z",
    validatedBy: "3",
    validationComment: "Ce ne sont pas des doublons, installations différentes",
    data: {
      koboId: "KBO-7890",
      location: "Douala, Bonabéri",
    },
    similarity: 72,
    confidence: 45,
  },
  {
    id: "task-006",
    type: "difference",
    status: "validated",
    priority: "high",
    title: "Écart de coordonnées GPS",
    description: "Position GPS différente de plus de 100m",
    assignedTo: "5",
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-04-01T15:30:00Z",
    completedAt: "2026-04-01T13:00:00Z",
    validatedAt: "2026-04-01T15:30:00Z",
    validatedBy: "3",
    data: {
      koboId: "KBO-1122",
      eneoId: "ENEO-1122",
      location: "Garoua, Centre",
      distanceMeters: 156,
    },
  },

  
  {
    id: "task-007",
    type: "new_kobo",
    status: "completed",
    priority: "medium",
    title: "Lot de 8 nouveaux compteurs",
    description: "Import massif de données terrain",
    assignedTo: "5",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T14:30:00Z",
    completedAt: "2026-04-01T14:30:00Z",
    data: {
      batchId: "BATCH-2026-04-01",
      count: 8,
      region: "Centre",
    },
  },
  {
    id: "task-008",
    type: "duplicate",
    status: "in_progress",
    priority: "high",
    title: "Doublon détecté - Zone Mokolo",
    description: "Deux compteurs avec le même numéro de série",
    assignedTo: "4",
    createdAt: "2026-04-01T11:00:00Z",
    updatedAt: "2026-04-01T16:00:00Z",
    data: {
      koboId: "KBO-7891",
      eneoId: "ENEO-7891",
      location: "Yaoundé, Mokolo",
    },
    sourceData: {
      id: "KBO-7891",
      name: "Compteur Commercial",
      address: "45 Avenue Mokolo",
      type: "Triphasé",
      power: "30kVA",
    },
    targetData: {
      id: "ENEO-7891",
      name: "Compteur Commercial",
      address: "45 Avenue Mokolo",
      type: "Triphasé",
      power: "30kVA",
    },
    similarity: 98,
    confidence: 95,
  },

  // Jeudi 26 (aujourd'hui)
  {
    id: "task-010",
    type: "duplicate",
    status: "pending",
    priority: "high",
    title: "Doublon détecté - Zone Makepe",
    description: "Doublon potentiel à vérifier",
    assignedTo: "4",
    createdAt: "2026-04-01T07:30:00Z",
    updatedAt: "2026-04-01T07:30:00Z",
    data: {
      koboId: "KBO-7892",
      eneoId: "ENEO-7892",
      location: "Douala, Makepe",
    },
    similarity: 85,
    confidence: 78,
  },
  {
    id: "task-011",
    type: "difference",
    status: "in_progress",
    priority: "medium",
    title: "Différence de consommation",
    description: "Écart de consommation anormal",
    assignedTo: "5",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T10:30:00Z",
    data: {
      koboId: "KBO-3456",
      eneoId: "ENEO-3456",
      location: "Yaoundé, Nsam",
    },
  },
  {
    id: "task-012",
    type: "new_kobo",
    status: "completed",
    priority: "low",
    title: "Lot de 12 nouveaux compteurs - Région Nord",
    description: "Import massif de données terrain",
    assignedTo: "5",
    createdAt: "2026-04-01T06:00:00Z",
    updatedAt: "2026-04-01T11:30:00Z",
    completedAt: "2026-04-01T11:30:00Z",
    data: {
      batchId: "BATCH-2026-04-01",
      count: 12,
      region: "Nord",
    },
  },
  {
    id: "task-013",
    type: "difference",
    status: "pending",
    priority: "high",
    title: "Écart de coordonnées GPS - Garoua",
    description: "Position GPS différente de plus de 100m",
    createdAt: "2026-04-01T08:30:00Z",
    updatedAt: "2026-04-01T08:30:00Z",
    data: {
      koboId: "KBO-1123",
      eneoId: "ENEO-1123",
      location: "Garoua, Centre",
      distanceMeters: 180,
    },
  },
  {
    id: "task-014",
    type: "duplicate",
    status: "validated",
    priority: "high",
    title: "Doublon validé - Zone Bastos",
    description: "Doublon traité et validé",
    assignedTo: "4",
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-04-01T14:00:00Z",
    completedAt: "2026-04-01T12:00:00Z",
    validatedAt: "2026-04-01T14:00:00Z",
    validatedBy: "3",
    data: {
      koboId: "KBO-2347",
      eneoId: "ENEO-2347",
      location: "Yaoundé, Bastos",
    },
    similarity: 92,
    confidence: 88,
  },
];

// Dashboard Statistics - Pour la semaine du 23 au 26 mars
export const mockDashboardStats: DashboardStats = {
  totalTasks: 524,
  pending: 95,
  inProgress: 68,
  completed: 361,
  validated: 312,
  rejected: 49,
  processingRate: 68.9,
  validationRate: 86.4,
  avgProcessingTime: 2.1,
};

// Agent Statistics - Basées sur la semaine
export const mockAgentStats: AgentStats[] = [
  {
    userId: "4",
    user: mockUsers[3],
    tasksAssigned: 42,
    tasksCompleted: 38,
    tasksValidated: 35,
    tasksRejected: 3,
    occupancyRate: 84,
    avgProcessingTime: 1.6,
    efficiency: 92,
  },
  {
    userId: "5",
    user: mockUsers[4],
    tasksAssigned: 45,
    tasksCompleted: 32,
    tasksValidated: 28,
    tasksRejected: 4,
    occupancyRate: 71,
    avgProcessingTime: 2.5,
    efficiency: 88,
  },
  {
    userId: "3",
    user: mockUsers[2],
    tasksAssigned: 58,
    tasksCompleted: 52,
    tasksValidated: 52,
    tasksRejected: 0,
    occupancyRate: 72,
    avgProcessingTime: 1.0,
    efficiency: 100,
  },
  {
    userId: "6",
    user: mockUsers[5],
    tasksAssigned: 25,
    tasksCompleted: 24,
    tasksValidated: 23,
    tasksRejected: 1,
    occupancyRate: 50,
    avgProcessingTime: 1.2,
    efficiency: 96,
  },
];

// Weekly Trend - Du 23 au 26 mars
export const mockWeeklyTrend: WeeklyTrend[] = [
  { date: "2026-04-01", completed: 48, validated: 42, rejected: 6 },
  { date: "2026-04-01", completed: 52, validated: 45, rejected: 7 },
  { date: "2026-04-01", completed: 58, validated: 51, rejected: 7 },
  { date: "2026-04-01", completed: 44, validated: 38, rejected: 6 },
];

// Recent Activity - Activités de la semaine
export const mockActivity: ActivityItem[] = [
  // Jeudi 26 mars
  {
    id: "act-001",
    type: "task_validated",
    description: "Tâche #014 validée par Paul Mvondo",
    timestamp: "2026-04-01T14:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-014",
  },
  {
    id: "act-002",
    type: "task_completed",
    description: "Lot de 12 nouveaux compteurs traité",
    timestamp: "2026-04-01T11:30:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-012",
  },
  {
    id: "act-003",
    type: "task_created",
    description: "Nouveau doublon détecté - Zone Makepe",
    timestamp: "2026-04-01T07:30:00Z",
    taskId: "task-010",
  },
  {
    id: "act-004",
    type: "task_rejected",
    description: "Réjetée - Différence consommation",
    timestamp: "2026-04-01T10:30:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-011",
  },
  {
    id: "act-005",
    type: "task_created",
    description: "Écart GPS détecté - Garoua",
    timestamp: "2026-04-01T08:30:00Z",
    taskId: "task-013",
  },

  // Mercredi 25 mars
  {
    id: "act-006",
    type: "task_validated",
    description: "Tâche #009 validée - Point Bali",
    timestamp: "2026-04-01T17:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-009",
  },
  {
    id: "act-007",
    type: "task_completed",
    description: "Lot de 8 compteurs traité",
    timestamp: "2026-04-01T14:30:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-007",
  },
  {
    id: "act-008",
    type: "task_created",
    description: "Doublon détecté - Zone Mokolo",
    timestamp: "2026-04-01T11:00:00Z",
    taskId: "task-008",
  },

  // Mardi 24 mars
  {
    id: "act-009",
    type: "task_rejected",
    description: "Tâche #005 rejetée - Zone Industrielle",
    timestamp: "2026-04-01T18:30:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-005",
  },
  {
    id: "act-010",
    type: "task_completed",
    description: "Données Eneo manquantes traitées",
    timestamp: "2026-04-01T17:00:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-004",
  },

  // Lundi 23 mars
  {
    id: "act-011",
    type: "task_validated",
    description: "Tâche #002 validée - Différence Bonanjo",
    timestamp: "2026-04-01T16:15:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-002",
  },
  {
    id: "act-012",
    type: "task_completed",
    description: "Doublon traité - Compteur #A2345",
    timestamp: "2026-04-01T10:30:00Z",
    userId: "4",
    user: mockUsers[3],
    taskId: "task-001",
  },
];

// GeoPoints for Map
export const mockGeoPoints: GeoPoint[] = [
  { id: "geo-001", lat: 3.8480, lng: 11.5021, type: "kobo", status: "completed", data: { name: "Point A - Mvan" } },
  { id: "geo-002", lat: 3.8550, lng: 11.5150, type: "eneo", status: "validated", data: { name: "Point B - Bastos" } },
  { id: "geo-003", lat: 3.8600, lng: 11.4900, type: "processed", status: "in_progress", data: { name: "Point C - Mokolo" } },
  { id: "geo-004", lat: 4.0511, lng: 9.7679, type: "kobo", status: "pending", data: { name: "Point D - Bonanjo" } },
  { id: "geo-005", lat: 4.0600, lng: 9.7800, type: "eneo", status: "completed", data: { name: "Point E - Makepe" } },
  { id: "geo-006", lat: 4.0450, lng: 9.7550, type: "kobo", status: "validated", data: { name: "Point F - Akwa" } },
  { id: "geo-007", lat: 5.9631, lng: 10.1591, type: "processed", status: "completed", data: { name: "Point G - Bali" } },
  { id: "geo-008", lat: 9.3265, lng: 13.3972, type: "kobo", status: "pending", data: { name: "Point H - Garoua" } },
];

// Regions
export const mockRegions: Region[] = [
  { id: "reg-001", name: "Centre", code: "CE", pointsCount: 465, completionRate: 79 },
  { id: "reg-002", name: "Littoral", code: "LT", pointsCount: 532, completionRate: 86 },
  { id: "reg-003", name: "Ouest", code: "OU", pointsCount: 318, completionRate: 63 },
  { id: "reg-004", name: "Nord", code: "NO", pointsCount: 201, completionRate: 48 },
  { id: "reg-005", name: "Sud", code: "SU", pointsCount: 148, completionRate: 72 },
  { id: "reg-006", name: "Est", code: "ES", pointsCount: 102, completionRate: 56 },
  { id: "reg-007", name: "Adamaoua", code: "AD", pointsCount: 91, completionRate: 49 },
  { id: "reg-008", name: "Nord-Ouest", code: "NW", pointsCount: 138, completionRate: 59 },
  { id: "reg-009", name: "Sud-Ouest", code: "SW", pointsCount: 171, completionRate: 68 },
  { id: "reg-010", name: "Extrême-Nord", code: "EN", pointsCount: 142, completionRate: 44 },
];

// Notifications - Mises à jour
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "new_task",
    title: "Nouvelle tâche assignée",
    message: "Un nouveau doublon a été détecté - Zone Makepe",
    isRead: false,
    createdAt: "2026-04-01T07:30:00Z",
    linkTo: "/processing/duplicates/task-010",
    isArchived: false
  },
  {
    id: "notif-002",
    type: "task_validated",
    title: "Tâche validée",
    message: "Votre traitement #014 a été validé",
    isRead: false,
    createdAt: "2026-04-01T14:00:00Z",
    linkTo: "/validation/task-014",
    isArchived: false
  },
  {
    id: "notif-003",
    type: "task_validated",
    title: "Tâche validée",
    message: "Lot de 12 compteurs traité avec succès",
    isRead: false,
    createdAt: "2026-04-01T11:30:00Z",
    linkTo: "/processing/task-012",
    isArchived: false
  },
  {
    id: "notif-004",
    type: "task_validated",
    title: "Validation effectuée",
    message: "La tâche #009 a été validée",
    isRead: true,
    createdAt: "2026-04-01T17:00:00Z",
    linkTo: "/validation/task-009",
    isArchived: false
  },
  {
    id: "notif-005",
    type: "task_rejected",
    title: "Tâche rejetée",
    message: "Le traitement #005 a été rejeté",
    isRead: true,
    createdAt: "2026-04-01T18:30:00Z",
    linkTo: "/validation/task-005",
    isArchived: false
  },
];

// Electric Regions (ENEO Organization)
export const mockElectricRegions: ElectricRegion[] = [
  { id: "er-001", name: "Région Électrique Douala Ouest", code: "RDUO", city: "Douala" },
  { id: "er-002", name: "Région Électrique Douala Est", code: "RDUE", city: "Douala" },
  { id: "er-003", name: "Région Électrique Douala Centre", code: "RDUC", city: "Douala" },
  { id: "er-004", name: "Région Électrique Yaoundé Nord", code: "RYN", city: "Yaoundé" },
  { id: "er-005", name: "Région Électrique Yaoundé Sud", code: "RYS", city: "Yaoundé" },
  { id: "er-006", name: "Région Électrique Yaoundé Centre", code: "RYC", city: "Yaoundé" },
  { id: "er-007", name: "Région Électrique Garoua", code: "RG", city: "Garoua" },
  { id: "er-008", name: "Région Électrique Bamenda", code: "RB", city: "Bamenda" },
  { id: "er-009", name: "Région Électrique Buea", code: "RBU", city: "Buea" },
  { id: "er-010", name: "Région Électrique Bertoua", code: "RBE", city: "Bertoua" },
];

// Task Stats by Region
export const mockTaskStatsByRegion: TaskStatsByRegion[] = [
  {
    region: mockElectricRegions[0],
    totalTasks: 112,
    pending: 18,
    inProgress: 12,
    completed: 82,
    validated: 72,
    rejected: 10,
    completionRate: 73,
  },
  {
    region: mockElectricRegions[1],
    totalTasks: 95,
    pending: 15,
    inProgress: 10,
    completed: 70,
    validated: 62,
    rejected: 8,
    completionRate: 74,
  },
  {
    region: mockElectricRegions[2],
    totalTasks: 78,
    pending: 12,
    inProgress: 8,
    completed: 58,
    validated: 52,
    rejected: 6,
    completionRate: 74,
  },
  {
    region: mockElectricRegions[3],
    totalTasks: 125,
    pending: 25,
    inProgress: 18,
    completed: 82,
    validated: 74,
    rejected: 8,
    completionRate: 66,
  },
  {
    region: mockElectricRegions[4],
    totalTasks: 114,
    pending: 25,
    inProgress: 20,
    completed: 69,
    validated: 62,
    rejected: 7,
    completionRate: 61,
  },
];

// Task Stats by City
export const mockTaskStatsByCity: TaskStatsByCity[] = [
  {
    city: "Douala",
    regions: mockElectricRegions.slice(0, 3),
    totalTasks: 285,
    pending: 45,
    completionRate: 74,
  },
  {
    city: "Yaoundé",
    regions: mockElectricRegions.slice(3, 6),
    totalTasks: 239,
    pending: 50,
    completionRate: 63,
  },
];

// Task Stats by Zone
export const mockTaskStatsByZone: TaskStatsByZone[] = [
  { zone: "Zone Résidentielle Nord", totalTasks: 125, completed: 92 },
  { zone: "Zone Commerciale", totalTasks: 98, completed: 71 },
  { zone: "Zone Industrielle", totalTasks: 76, completed: 52 },
  { zone: "Zone Administrative", totalTasks: 45, completed: 34 },
  { zone: "Zone Rurale", totalTasks: 68, completed: 48 },
];

// Task Stats by Exploitation
export const mockTaskStatsByExploitation: TaskStatsByExploitation[] = [
  { exploitationId: "exp-001", exploitationName: "Exploitation Douala Centre", totalTasks: 62, completed: 46, avgProcessingTime: 1.9 },
  { exploitationId: "exp-002", exploitationName: "Exploitation Douala Ouest", totalTasks: 54, completed: 40, avgProcessingTime: 1.7 },
  { exploitationId: "exp-003", exploitationName: "Exploitation Yaoundé Nord", totalTasks: 68, completed: 45, avgProcessingTime: 2.1 },
  { exploitationId: "exp-004", exploitationName: "Exploitation Yaoundé Centre", totalTasks: 62, completed: 41, avgProcessingTime: 2.0 },
  { exploitationId: "exp-005", exploitationName: "Exploitation Garoua", totalTasks: 41, completed: 26, avgProcessingTime: 2.5 },
];